---
- name: Install Xorg base
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xrdb

- name: Install optional xorg tools
  pacman:
    name:
      - xorg-xmodmap
      - xorg-xrandr
      - xorg-xev
      - xorg-xset
      - xorg-xinput
  when: not minimal

- name: Caps -> Ctrl in Xorg
  copy: src=files/xorg-no-caps dest=/etc/X11/xorg.conf.d/00-keyboard.conf mode=644

- name: Blacklist nouveau Xorg driver
  kernel_blacklist: name=nouveau state=present
  when: model in ["Vostro 3700"]

- name: Do not blacklist nouveau Xorg driver
  kernel_blacklist: name=nvidia state=absent
  when: model in ["Vostro 3700"]

- name: Set up Xorg for Vostro 3700
  pacman:
    name:
      - xf86-input-libinput
  when: model == "Vostro 3700"

- name: Set up Xorg for T4xxs
  pacman:
    name:
      - xf86-video-intel
      - libva-intel-driver
  when: model in ["T460s", "T470s"]

- name: Add UXA override 
  copy: src=files/20-intel.conf dest=/etc/X11/xorg.conf.d/20-intel.conf mode=644
  when: model in ["T460s", "T470s"]

- name: Set up Xorg for ThinkPad
  pacman:
    name:
      - xf86-input-libinput
  when: model in ["T460s", "T470s", "X1 Carbon"]

- name: Set up Xorg for nouveau-using laptops
  pacman:
    name:
      - xf86-video-nouveau
      - xf86-input-libinput
  when: model in ["XPS 8500"]

- name: Remove intel video for those formerly using only integrated
  pacman:
    state: absent
    extra_args: "--recursive"
    name:
      - xf86-video-intel
      - libva-intel-driver
  when: model not in ["T460s", "T470s"]

- name: Set up Xorg for Parallels
  pacman: name=xf86-video-vesa state=present
  when: model == "Parallels"

- name: Install VMVGA Xorg driver
  pacman: name=xf86-video-vmware state=present
  when: model == "VirtualBox"

- name: Install VirtualBox guest utilities
  # Needs to be from the AUR as there's no guarantee that the headers will come
  # from pacman repos
  aur: name={{ item }} skip_installed=yes
  with_items:
    - virtualbox-guest-utils
    - "{{ kernel }}-headers"  # needed for virtualbox-guest-dkms which is
  become: yes
  become_user: makepkg
                              # pulled in by virtualbox-guest-utils
  when: model == "VirtualBox"

- name: Set up autoloading of VirtualBox modules
  copy: src=files/virtualbox/guest-modules dest=/etc/modules-load.d/virtualbox-guest.conf
  when: model == "VirtualBox"

- name: Configure vboxservice
  service: name=vboxservice state=started enabled=yes
  when: model == "VirtualBox"

- name: Install depmod-all
  copy: src=files/bin/depmod-all dest=/usr/local/bin/depmod-all mode=0755

- name: Depmod
  command: depmod-all
  changed_when: false
